name: Algorithm-Distillation

on: [ push, pull_request ]

jobs:
  build:
    # Skip CI if [ci skip] in the commit message
    if: "! contains(toJSON(github.event.commits.*.message), '[ci skip]')"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ "3.9", "3.10" ]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip3 install torch --extra-index-url https://download.pytorch.org/whl/cpu
          pip install .[test]
      - name: Lint with flake8
        run: |
          make lint
      - name: Type-check
        run: |
          make type
      - name: Test using pytest
        run: |
          make pytest
